(() => {
  window.MUSHI_AI_POLICY = {
  "version": 15,
  "source": "color-counter-random-deck-search-v8",
  "training": {
    "seed": 20260926,
    "targetOpponent": "colorBlessing",
    "approximateSimulator": true,
    "colorWeaknessMode": true,
    "games": 932000,
    "candidates": 2600,
    "base": {
      "winRate": 0.7325,
      "score": 2.2027,
      "record": {
        "wins": 10255,
        "losses": 3680,
        "draws": 65,
        "games": 14000
      }
    },
    "bestDeck": {
      "ids": [
        701,
        701,
        703,
        703,
        8,
        212,
        426,
        702,
        511,
        511,
        824,
        212,
        513,
        513,
        824,
        607,
        253,
        253,
        60,
        426
      ],
      "names": [
        "オオスズメバチ（女王）",
        "オオスズメバチ（女王）",
        "オオスズメバチ",
        "オオスズメバチ",
        "オオスズメバチ",
        "キアシナガバチ",
        "メンガタクワガタ",
        "タランチュラホーク",
        "モンスズメバチ",
        "モンスズメバチ",
        "ヤマトハキリバチ",
        "キアシナガバチ",
        "クロスズメバチ",
        "クロスズメバチ",
        "ヤマトハキリバチ",
        "エゾオナガバチ",
        "電気虫の稲妻",
        "電気虫の稲妻",
        "ニホンミツバチ",
        "メンガタクワガタ"
      ],
      "winRate": 0.9559,
      "score": 2.8695,
      "record": {
        "wins": 13383,
        "losses": 598,
        "draws": 19,
        "games": 14000
      }
    },
    "top": [
      {
        "ids": [
          701,
          701,
          703,
          703,
          8,
          212,
          426,
          702,
          511,
          511,
          824,
          212,
          513,
          513,
          824,
          607,
          253,
          253,
          60,
          426
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "キアシナガバチ",
          "メンガタクワガタ",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "ヤマトハキリバチ",
          "キアシナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "ヤマトハキリバチ",
          "エゾオナガバチ",
          "電気虫の稲妻",
          "電気虫の稲妻",
          "ニホンミツバチ",
          "メンガタクワガタ"
        ],
        "winRate": 0.9559,
        "score": 2.8695
      },
      {
        "ids": [
          701,
          701,
          520,
          703,
          8,
          8,
          824,
          702,
          511,
          511,
          212,
          212,
          513,
          513,
          124,
          830,
          558,
          253,
          60,
          824
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "セイヨウオオマルハナバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "ヤマトハキリバチ",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "キアシナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "塵芥虫の爆熱弾",
          "パンダアリバチ",
          "燻煙の迎撃",
          "電気虫の稲妻",
          "ニホンミツバチ",
          "ヤマトハキリバチ"
        ],
        "winRate": 0.9467,
        "score": 2.844
      },
      {
        "ids": [
          701,
          701,
          703,
          703,
          8,
          8,
          124,
          702,
          511,
          511,
          212,
          212,
          520,
          513,
          558,
          824,
          253,
          253,
          463,
          824
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "塵芥虫の爆熱弾",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "キアシナガバチ",
          "セイヨウオオマルハナバチ",
          "クロスズメバチ",
          "燻煙の迎撃",
          "ヤマトハキリバチ",
          "電気虫の稲妻",
          "電気虫の稲妻",
          "伏魔の蟲噛み",
          "ヤマトハキリバチ"
        ],
        "winRate": 0.9471,
        "score": 2.8429
      },
      {
        "ids": [
          701,
          701,
          703,
          703,
          8,
          8,
          702,
          463,
          511,
          511,
          212,
          212,
          513,
          513,
          463,
          405,
          253,
          253,
          60,
          607
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "タランチュラホーク",
          "伏魔の蟲噛み",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "キアシナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "伏魔の蟲噛み",
          "コロギス",
          "電気虫の稲妻",
          "電気虫の稲妻",
          "ニホンミツバチ",
          "エゾオナガバチ"
        ],
        "winRate": 0.944,
        "score": 2.8345
      },
      {
        "ids": [
          701,
          701,
          703,
          124,
          8,
          8,
          702,
          702,
          511,
          511,
          212,
          212,
          513,
          513,
          426,
          124,
          520,
          253,
          463,
          824
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "塵芥虫の爆熱弾",
          "オオスズメバチ",
          "オオスズメバチ",
          "タランチュラホーク",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "キアシナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "メンガタクワガタ",
          "塵芥虫の爆熱弾",
          "セイヨウオオマルハナバチ",
          "電気虫の稲妻",
          "伏魔の蟲噛み",
          "ヤマトハキリバチ"
        ],
        "winRate": 0.9415,
        "score": 2.8256
      },
      {
        "ids": [
          701,
          701,
          703,
          703,
          8,
          426,
          702,
          702,
          511,
          511,
          212,
          212,
          513,
          513,
          405,
          53,
          253,
          253,
          60,
          824
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "メンガタクワガタ",
          "タランチュラホーク",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "キアシナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "コロギス",
          "セイヨウミツバチ",
          "電気虫の稲妻",
          "電気虫の稲妻",
          "ニホンミツバチ",
          "ヤマトハキリバチ"
        ],
        "winRate": 0.9375,
        "score": 2.8143
      },
      {
        "ids": [
          701,
          701,
          703,
          703,
          8,
          8,
          558,
          702,
          511,
          511,
          212,
          607,
          513,
          513,
          212,
          824,
          253,
          117,
          60,
          824
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "燻煙の迎撃",
          "タランチュラホーク",
          "モンスズメバチ",
          "モンスズメバチ",
          "キアシナガバチ",
          "エゾオナガバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "キアシナガバチ",
          "ヤマトハキリバチ",
          "電気虫の稲妻",
          "退魔の蚊遣り火",
          "ニホンミツバチ",
          "ヤマトハキリバチ"
        ],
        "winRate": 0.9359,
        "score": 2.8096
      },
      {
        "ids": [
          701,
          701,
          124,
          703,
          8,
          8,
          702,
          702,
          253,
          511,
          212,
          830,
          513,
          513,
          405,
          405,
          824,
          253,
          60,
          607
        ],
        "names": [
          "オオスズメバチ（女王）",
          "オオスズメバチ（女王）",
          "塵芥虫の爆熱弾",
          "オオスズメバチ",
          "オオスズメバチ",
          "オオスズメバチ",
          "タランチュラホーク",
          "タランチュラホーク",
          "電気虫の稲妻",
          "モンスズメバチ",
          "キアシナガバチ",
          "パンダアリバチ",
          "クロスズメバチ",
          "クロスズメバチ",
          "コロギス",
          "コロギス",
          "ヤマトハキリバチ",
          "電気虫の稲妻",
          "ニホンミツバチ",
          "エゾオナガバチ"
        ],
        "winRate": 0.9354,
        "score": 2.8085
      }
    ]
  },
  "archetypes": {
    "aquatic": {
      "comboWeight": 1,
      "cheapDeployBonus": 0,
      "finisherResourceTarget": 6,
      "blueBaitFloor": 5,
      "bloodPactWeight": 1.4,
      "rgbBaitPriority": 9,
      "bloodPactTerritoryWeight": 1.15,
      "engineBaitPriority": 8,
      "aquaticCheapBonus": 2.5,
      "bounceThreatThreshold": 7,
      "reverseSwapDelta": 3,
      "resourceTarget": 4,
      "aggression": 1.495,
      "directAttackWeight": 1.497,
      "tempSummonBaitFloor": 5,
      "tempSummonMinValue": 16.284,
      "preserveWeight": 1.256,
      "removalWeight": 1.133,
      "aceWeight": 1.059,
      "deployThreshold": 5.7
    },
    "armyAnt": {
      "comboWeight": 0.82,
      "cheapDeployBonus": 0,
      "finisherResourceTarget": 4,
      "blueBaitFloor": 2,
      "bloodPactWeight": 1.681,
      "rgbBaitPriority": 9.378,
      "bloodPactTerritoryWeight": 0.97,
      "engineBaitPriority": 8,
      "aquaticCheapBonus": 0,
      "bounceThreatThreshold": 7.634,
      "reverseSwapDelta": 3.832,
      "resourceTarget": 6,
      "aggression": 1.45,
      "directAttackWeight": 1.689,
      "tempSummonBaitFloor": 7,
      "tempSummonMinValue": 11.47,
      "preserveWeight": 1.022,
      "removalWeight": 0.756,
      "aceWeight": 1.816,
      "deployThreshold": 4.46
    },
    "hercules": {
      "comboWeight": 0.6,
      "cheapDeployBonus": 0,
      "finisherResourceTarget": 6,
      "blueBaitFloor": 3,
      "bloodPactWeight": 0.709,
      "rgbBaitPriority": 8.482,
      "bloodPactTerritoryWeight": 1.292,
      "engineBaitPriority": 8.563,
      "aquaticCheapBonus": 0.006,
      "bounceThreatThreshold": 8.814,
      "reverseSwapDelta": 3.433,
      "resourceTarget": 6,
      "aggression": 1.671,
      "directAttackWeight": 1.196,
      "tempSummonBaitFloor": 7,
      "tempSummonMinValue": 16.293,
      "preserveWeight": 1.8,
      "removalWeight": 1.591,
      "aceWeight": 1.63,
      "deployThreshold": 5.538
    },
    "sumatra": {
      "comboWeight": 0.799,
      "cheapDeployBonus": 0,
      "finisherResourceTarget": 7,
      "blueBaitFloor": 2,
      "bloodPactWeight": 1.072,
      "rgbBaitPriority": 9,
      "bloodPactTerritoryWeight": 1.15,
      "engineBaitPriority": 8,
      "aquaticCheapBonus": 1.263,
      "bounceThreatThreshold": 7.005,
      "reverseSwapDelta": 3.499,
      "resourceTarget": 6,
      "aggression": 1.2,
      "directAttackWeight": 1.599,
      "tempSummonBaitFloor": 6,
      "tempSummonMinValue": 9.688,
      "preserveWeight": 1.304,
      "removalWeight": 1.225,
      "aceWeight": 1.818,
      "deployThreshold": 5.627
    },
    "bee": {
      "comboWeight": 0.941,
      "cheapDeployBonus": 0.892,
      "finisherResourceTarget": 5,
      "blueBaitFloor": 2,
      "bloodPactWeight": 0.952,
      "rgbBaitPriority": 9.693,
      "bloodPactTerritoryWeight": 1.274,
      "engineBaitPriority": 7.307,
      "aquaticCheapBonus": 0.394,
      "bounceThreatThreshold": 6.439,
      "reverseSwapDelta": 2.943,
      "resourceTarget": 6,
      "aggression": 1.22,
      "directAttackWeight": 1.77,
      "tempSummonBaitFloor": 7,
      "tempSummonMinValue": 12.43,
      "preserveWeight": 0.879,
      "removalWeight": 0.95,
      "aceWeight": 1.837,
      "deployThreshold": 6.539
    },
    "mimicAggro": {
      "comboWeight": 1.747,
      "cheapDeployBonus": 0.9,
      "finisherResourceTarget": 5,
      "blueBaitFloor": 3,
      "bloodPactWeight": 0.822,
      "rgbBaitPriority": 8.662,
      "bloodPactTerritoryWeight": 1.043,
      "engineBaitPriority": 8.703,
      "aquaticCheapBonus": 0.164,
      "bounceThreatThreshold": 8.139,
      "reverseSwapDelta": 3.249,
      "resourceTarget": 4,
      "aggression": 1.89,
      "directAttackWeight": 1.595,
      "tempSummonBaitFloor": 5,
      "tempSummonMinValue": 16.123,
      "preserveWeight": 1.248,
      "removalWeight": 0.75,
      "aceWeight": 1.819,
      "deployThreshold": 7.179
    },
    "colorBlessing": {
      "comboWeight": 1.517,
      "cheapDeployBonus": 0,
      "finisherResourceTarget": 6,
      "blueBaitFloor": 3,
      "bloodPactWeight": 1.3,
      "rgbBaitPriority": 9.393,
      "bloodPactTerritoryWeight": 1.202,
      "aquaticCheapBonus": 0,
      "bounceThreatThreshold": 6.02,
      "reverseSwapDelta": 3.434,
      "resourceTarget": 4,
      "aggression": 1.066,
      "directAttackWeight": 1.905,
      "tempSummonBaitFloor": 4,
      "tempSummonMinValue": 14.667,
      "preserveWeight": 1.433,
      "removalWeight": 1.305,
      "aceWeight": 1.397,
      "deployThreshold": 3.713
    },
    "generic": {
      "resourceTarget": 5,
      "blueBaitFloor": 2,
      "aggression": 1.2,
      "directAttackWeight": 1.35,
      "tempSummonBaitFloor": 5,
      "tempSummonMinValue": 11,
      "preserveWeight": 1.15,
      "removalWeight": 1.15,
      "aceWeight": 1.2,
      "deployThreshold": 7
    },
    "colorCounter": {
      "comboWeight": 1.313,
      "cheapDeployBonus": 2.388,
      "finisherResourceTarget": 6,
      "blueBaitFloor": 5,
      "bloodPactWeight": 0.877,
      "rgbBaitPriority": 13.694,
      "bloodPactTerritoryWeight": 1.32,
      "engineBaitPriority": 4.37,
      "aquaticCheapBonus": 0.206,
      "bounceThreatThreshold": 7.883,
      "reverseSwapDelta": 4.03,
      "resourceTarget": 6,
      "aggression": 1.59,
      "directAttackWeight": 1.025,
      "tempSummonBaitFloor": 6,
      "tempSummonMinValue": 9.668,
      "preserveWeight": 1.773,
      "removalWeight": 0.798,
      "aceWeight": 1.972,
      "deployThreshold": 6.997
    }
  }
};
})();
